# Generated by Django 5.0.1 on 2024-04-14 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecords',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
